### ISSUE TITLE
[BUG] Bad release notes for 2.5.0

### ISSUE THREAD

**Issue by cthtrifork** [opensearch-project/opensearch-k8s-operator#721]
### What is the bug?
_A clear and concise description of the bug._

https://github.com/opensearch-project/opensearch-k8s-operator/compare/v2.4.0...v2.5.0 contains 66 commits with new features.

### How can one reproduce the bug?
_Steps to reproduce the behavior._

Look at https://github.com/opensearch-project/opensearch-k8s-operator/releases/tag/v2.5.0
![image](https://github.com/opensearch-project/opensearch-k8s-operator/assets/73483987/d30495fc-d466-4e39-a9e1-77d41a8c00ce)

### What is the expected behavior?
_A clear and concise description of what you expected to happen._

Should highlight changes like in https://github.com/opensearch-project/opensearch-k8s-operator/releases/tag/v2.4.0

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._
I am guessing it has not been a priority yet, due to the migration, but with this ticket we can keep track of progress.

**Comment by prudhvigodithi** [comment]
[Triage]
Thanks @cthtrifork, we want to get the release out to make the operator is usable due to this issue https://github.com/opensearch-project/opensearch-k8s-operator/issues/709, TLDR the operator images are removed from `opsterio/opensearch-operator` ECR repo and users (new and existing) are not able to run the operator, to fix this 2.5.0 was released urgently to ensure the images are now part of official opensearch org docker and ECR registries. I will shortly update the release notes for 2.5.0 and moving forward will make sure every release will have a proper release notes.
Thanks 
@bbarani @swoehrl-mw

**Comment by prudhvigodithi** [comment]
I have added the release notes https://github.com/opensearch-project/opensearch-k8s-operator/releases/tag/v2.5.0, please check. Closing this issue @cthtrifork please re-open if required.
Thanks
