### ISSUE TITLE
Document procedure for renewing certificates

### ISSUE THREAD

**Issue by trondhindenes** [opensearch-project/opensearch-k8s-operator#724]
### Is your feature request related to a problem?
The operator currently generates self-signed certificates with 1 year validity. There's no automated cert renewal process.
Please document how to perform a manual renewal of certificates, as this is an extremely critical operational task

### What solution would you like?
A tested and well-documented process for renewing certificates

**Comment by mrvdcsg** [comment]
In addition to self-signed, I think the process for renewing certificates needs documented in general. I would expect updating the certificate secret to cause a rolling restart but it does not which means manual intervention is needed annually to replace certificates (unless this was fixed in operator 2.5 as we have not tested that yet for this use case).

**Comment by prudhvigodithi** [comment]
[Triage]
The documentation PR about warning regarding cert expiration is added via the PR https://github.com/opensearch-project/opensearch-k8s-operator/pull/725. Closing this please re-open if required.
Thanks 
@trondhindenes @mrvdcsg
