### ISSUE TITLE
[BUG] Parallel Cluster Recovery didn't work

### ISSUE THREAD

**Issue by pawellrus** [opensearch-project/opensearch-k8s-operator#730]
Version: 2.4.0, 2.5.1
Function: [Parallel Cluster Recovery](https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/userguide/main.md#cluster-recovery)

**Description:**
After performing upgrade of managed k8s cluster, the hosted opensearch cluster stuck in "waiting for quorum" state.

**Scenario:**
Performed k8s cluster upgrade. During upgrade all nodes was recreated and pods was rescheduled TWISE at the same time.

**Expected behaviour:**
All nodes should be started at the same time. (statefulset has podManagementPolicy: Parallel)
Cluster recovered.

**Actual behaviour:**
Only one node of cluster is started. Other nodes are not starting. Quorum cannot be achieved.
Operator does nothing with this situation. Statefulset has podManagementPolicy: OrderedReady

**Thoughts:**
I fixed this problem by scaling down operator deployment to 0 and then manually recreating STS with ***podManagementPolicy: Parallel***.

Not sure that I can reproduce that case again. Maybe operator should have some manual trigger to perform parallel cluster restoration in cases like that?

**Comment by Links2004** [comment]
Hi have seen the same behaviour for a change from 2.10.0 to 2.11.1.
stuck in `waiting for quorum` until manual intervention.

**Comment by pstast** [comment]
Just had the same issue. All my k8s nodes crashed, but after k8s recovery, OpenSearch cluster did not recovered. Only one pod from statefulset started. I also had to stop the operator and manually change `podManagementPolicy: Parallel` so that all pods started and OpenSearch recovered.

Unfortunately I did not find anything in logs, there was no error. Operator just did nothing. It did not switch to parallel recovery.

**Comment by prudhvigodithi** [comment]
[Triage]
There a PR contributed by @swoehrl-mw https://github.com/opensearch-project/opensearch-k8s-operator/pull/366 to handle the cluster recovery. When used the latest version of the operator do you guys still see this issue?
@pawellrus @Links2004 @pstast 

Thanks
@bbarani

**Comment by pawellrus** [comment]
> [Triage] There a PR contributed by @swoehrl-mw #366 to handle the cluster recovery. When used the latest version of the operator do you guys still see this issue? @pawellrus @Links2004 @pstast
> 
> Thanks @bbarani

Hello, @prudhvigodithi
This issue persists on 2.4.0 and 2.5.1 in my environment.

**Comment by pstast** [comment]
@prudhvigodithi I also encountered this problem with the last version (2.5.1)

**Comment by prudhvigodithi** [comment]
@swoehrl-mw can you please take a look at this? Thanks

**Comment by swoehrl-mw** [comment]
@pstast @pawellrus @Links2004 
To verify:
* Do you have PVCs configured as storage?
* Is each nodepool configured with at least 3 pods/replicas?
* The parallelRecovery mode is not disabled (via helm values)?

There are some points in the logic where the operator can skip the recovery due to errors, but these should all produce some log.

**Comment by pawellrus** [comment]
@swoehrl-mw answer to all questions - yes.
But dashboards has only two replicas.
Btw, I use ArgoCD for deployment.

**Comment by swoehrl-mw** [comment]
Hi all, I did some looking through the code and testing and I think I can reproduce the problem and found the cause:
Disaster recovery does not engage if the operator is doing an upgrade. The problem is that there is a bug in the detection of an upgrade where, due to status information being unclear, it thinks an upgrade is still in progress although it is long finished and so does not engage.
I'll create a PR with a fix in the next few days.

cc @prudhvigodithi

**Comment by prudhvigodithi** [comment]
Thanks @swoehrl-mw we can target this after [v2.6.0](https://github.com/opensearch-project/opensearch-k8s-operator/issues/776) release.
@bbarani @swoehrl-mw
